# Streamlit Secrets Configuration
# Rename this file to 'secrets.toml' and add your actual API key

# OpenRouter API Key (required)
OPENROUTER_API_KEY = "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"

# Optional: Logging level
LOG_LEVEL = "INFO"

# Note: Never commit the actual secrets.toml file to version control
# Add secrets.toml to your .gitignore file